### ISSUE TITLE
[ENHANCEMENT] Add button to hide irrelevant steps for 2nd+ character

### ISSUE THREAD

**Issue by BeardyBarber** [Blemming/PoE-newleague#29]
While levelling second+ character during league some areas can be skipped due to being visited only to do lab trial. 

It would be great to have Hide/Show button to skip these steps.

Let me know if you would be interested in implementing that, I can help with marking what steps / part of steps can be skipped.

**Comment by Blemming** [comment]
That's a good Idea, if you can flag which steps are skippable I'll look into implementing it, sorry taking so long to see this issue haha

**Comment by BeardyBarber** [comment]
Here are parts/point that needs to be hidden for subsequent characters based on `data.json` with numeration from site. 
Code fragment can be copied and search for ease of adding tags or something.

### ACT 1
14.  ` , do **trial** on first level ` 
21. ` (dont forget crafting) `

###ACT 2 
7. `"*The Chamber of Sins level 2* do the **trial** it is most likely north",` - point 6 and 8 needs refactor as this is the only point with **The Chamber of Sins level 2** name 
10. ` ![Waypoint](/images/waypoint.png)<span class=\"wp\">Waypoint</span> to *The Crossroads* ⟶ South to *The Fellshrine Ruins*`
11. `"Find *The Crypt*, *The Crypt* loops around ⟶ **trial** then log out",`  - both points should be hidden

###ACT 3
3. ` **trial**` 
6. `*The Catacombs* do **trial** log out`
11. ` get Crafting`
16. ` get Crafting`
20. `![Waypoint](/images/waypoint.png)<span class=\"wp\">Waypoint</span> *The Imperial Gardens* do **trial** get Crafting, `
### ACT 4
2. `, get Crafting `
4. ` get ![Waypoint](/images/waypoint.png)<span class=\"wp\">Waypoint</span> and Crafting ![Waypoint](/images/waypoint.png)<span class=\"wp\">Waypoint</span> town get passive point then `
17. ` get Crafting in *The Ascent*,`


### ACT 5
9. `and Crafting `

###ACT 6
7. ` do **trial**`
9. `, get Crafting`
16. ` get Crafting,`

###ACT 7
4. ` do **trial** get Crafting`
6. ` get Crafting and`
8. ` ⟶ *The Chamber of Sins level2*`
9. `The Chamber of Sins level2* do the **trial** ⟶ *The Den*` - whole point needs to be gone
16. ` and Crafting`
18. ` get crafting and`
21. ` (Don't forget Crafting)` - also `Ascend` missing markdown as location
23. ` get Crafting`


###ACT 8 
4. `and crafting `
10. ` get Crafting`
15. ` get crafting` 
20. ` to do **Trial** and get Crafting`

###ACT 9 
2. ` and crafting` 
7. ` do the **trial** get crafting ` - also locations names The tunnel(s) and The Quarry are not marked as all other locations (missing markdown *)
8. ` get Crafting and` - also BUG: We were in The Quarry in previous point so part `The Tunnel* ⟶ ` can be deleted

###ACT 10 
8. ` do the **Trial**`
10. `, get Crafting `
14. `, get Crafting ` 
16. `, get movement speed Crafting North West of city`

**Comment by Blemming** [comment]
Thanks ! this is super helpful!. I have been working on the implementation to hide parts of a step, but now I need to figure out how I want to manage if a full step need to be hidden.

**Comment by Blemming** [comment]
This should work, its a little check box in the side menu. If there are any issues put them here 👍

**Comment by BeardyBarber** [comment]
Tests - PASS :) 
Thank you for new feature :)
